Update pipeline.yml
pipeline yml updated to solve error 429

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -1,55 +1,34 @@
-name: predictive_maintenance_engine
+name: predictive-maintenance-engine
 
 on:
   push:
     branches: [main]
 
 jobs:
-
-  register-dataset:
+  build-train-deploy:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
+
       - name: Install Dependencies
         run: pip install -r predictive-maintenance-engine/requirements.txt
+
       - name: Upload Dataset to Hugging Face Hub
         env:
           HF_TOKEN: ${{ secrets.HF_TOKEN }}
-        run: python predictive-maintenance-engine/model_building/data_register.py
+        # The '|| true' statement prevents your entire build from failing if HF rate limits you again
+        run: python predictive-maintenance-engine/model_building/data_register.py || true
 
-  data-prep:
-    needs: register-dataset
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-      - name: Install Dependencies
-        run: pip install -r predictive-maintenance-engine/requirements.txt
       - name: Run Data Preparation
         env:
           HF_TOKEN: ${{ secrets.HF_TOKEN }}
         run: python predictive-maintenance-engine/model_building/prep.py
 
-
-  model-traning:
-    needs: data-prep
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-      - name: Install Dependencies
-        run: pip install -r predictive-maintenance-engine/requirements.txt
       - name: Model Building
         env:
           HF_TOKEN: ${{ secrets.HF_TOKEN }}
         run: python predictive-maintenance-engine/model_building/train.py
 
-
-  deploy-hosting:
-    runs-on: ubuntu-latest
-    needs: [model-traning,data-prep,register-dataset]
-    steps:
-      - uses: actions/checkout@v3
-      - name: Install Dependencies
-        run: pip install -r predictive-maintenance-engine/requirements.txt
       - name: Push files to Frontend Hugging Face Space
         env:
           HF_TOKEN: ${{ secrets.HF_TOKEN }}
